image:
  name: antora/antora:3.0.0
pages:
  stage: deploy
  only:
  - main@antora/demo/docs-site
  cache:
    paths:
    - .cache/
  script:
  - antora --fetch --cache-dir .cache/antora --attribute page-pagination= --redirect-facility gitlab --to-dir public antora-playbook.yml
  artifacts:
    paths:
    - public/
